trigger:
 - main
 
variables:
  vmImageName: 'ubuntu-latest'
  location: 'Korea Central'
  subscription: 'svcconn4lds'

pool:
  vmImage: $(vmImageName)

steps:
- task: Bash@3
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      set -eu  # fail on error
      curl -SL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" --output terraform.zip
      #echo "${TERRAFORM_DOWNLOAD_SHA} terraform.zip" | sha256sum -c -
      unzip "terraform.zip"
      sudo mv terraform /usr/local/bin
      terraform --version
      rm terraform.zip

- task: Bash@3
  displayName: 'Terraform Init'
  env:
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    script: |
      set -euo pipefail    
      echo "Initialize"
      terraform init \
        -input=false \
        -backend-config="resource_group_name=${TF_STORAGE_RG}" \
        -backend-config="storage_account_name=${TF_STORAGE_ACCOUNT}" \
        -backend-config="container_name=${TF_STORAGE_BLOB_CONTAINER}" \
        -backend-config="key=${TF_STORAGE_BLOB_NAME}" 
    
      echo "Sanity Check"
      terraform validate
    
      echo "Show Terraform Version and Providers"
      terraform -v
      terraform providers

- task: Bash@3
  displayName: 'Terraform Plan'
  env:
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
  inputs:
    targetType: 'inline'
    script: |
      set -euo pipefail      
      terraform plan \
      -input=false \
      -out ${BUILD_BUILDNUMBER}.tfplan
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Bash@3
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
  inputs:
    targetType: 'inline'
    #workingDirectory: $(project_folder)
    workingDirectory: $(System.DefaultWorkingDirectory)
    script: |
      set -euo pipefail
      terraform apply \
      -input=false \
      ${BUILD_BUILDNUMBER}.tfplan